services:
  postgres_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # ✅ PERSISTENCIA (NUEVO)

  redis_broker:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  authors_service:
    build: ./authors_service
    command: /wait-for-it.sh postgres_db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./authors_service:/code
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db:5432/library_db
      REDIS_URL: redis://redis_broker:6379/0
    depends_on:
      - postgres_db
      - redis_broker

  books_service:
    build: ./books_service
    command: /wait-for-it.sh postgres_db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./books_service:/code
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db:5432/library_db
      REDIS_URL: redis://redis_broker:6379/0
    depends_on:
      - postgres_db
      - redis_broker

volumes:
  postgres_data:   # ✅ (NUEVO) define el volumen nombrado
